
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
  namespace: jdnotes
  labels:
    db: elasticsearch             #设置 pv 的 label 标签
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /home/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node
              operator: In
              values:
                - node2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: jdnotes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      db: elasticsearch           #根据 Label 选择对应 PV

#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: elasticsearch-config
#  namespace: jdnotes
#data:
#  elasticsearch.yml: |
#    network.host: 0.0.0.0
#    http.port: 9200
#    path.data: /data
#    http.cors.enabled: true
#    http.cors.allow-origin: /.*/