---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: jdnotes
  labels:
    db: mysql             #设置 pv 的 label 标签
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /home/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
          operator: In
          values:
          - node1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: jdnotes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      db: mysql           #根据 Label 选择对应 PV

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: jdnotes
  labels:
    app: mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4
    [mysqld]
    max_connections = 2000
    secure_file_priv=/var/lib/mysql
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

